package org.koitharu.kotatsu.parsers.model

public enum class SortOrder {
	UPDATED,
	UPDATED_ASC,
	POPULARITY,
	POPULARITY_ASC,
	RATING,
	RATING_ASC,
	NEWEST,
	NEWEST_ASC,
	ALPHABETICAL,
	ALPHABETICAL_DESC,
	ADDED,
	ADDED_ASC,
	RELEVANCE,
	POPULARITY_HOUR,
	POPULARITY_TODAY,
	POPULARITY_WEEK,
	POPULARITY_MONTH,
	POPULARITY_YEAR,
}
