name: 🌐 Source request
description: Suggest a new source for Kotatsu
labels: [ source request ]
body:

    -   type: markdown
        attributes:
            value: Please specify source **name** and **language** in the issue title
    -   type: input
        id: name
        attributes:
            label: Source name
            placeholder: |
                Example: "Example Scans"
        validations:
            required: true

    -   type: input
        id: link
        attributes:
            label: Source link
            placeholder: |
                Example: "https://example.org"
        validations:
            required: true

    -   type: input
        id: language
        attributes:
            label: Language
            placeholder: |
                Example: "English"
        validations:
            required: true

    -   type: textarea
        id: other-details
        attributes:
            label: Other details
            placeholder: |
                Additional details and attachments.

    -   type: checkboxes
        id: acknowledgements
        attributes:
            label: Acknowledgements
            options:
                -   label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
                    required: true
                -   label: I have checked that the source does not already exist on the app.
                    required: true
                -   label: I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
                    required: true
