name: 🗑 Source removal request
description: Scanlators can request their site to be removed
labels: [ source removal ]
body:

    -   type: input
        id: link
        attributes:
            label: Source link
            placeholder: |
                Example: "https://example.org"
        validations:
            required: true

    -   type: textarea
        id: other-details
        attributes:
            label: Other details (reason for removal, etc)
            placeholder: |
                Additional details and attachments.

    -   type: checkboxes
        id: requirements
        attributes:
            label: Requirements
            description: Your request will be denied if you don't meet these requirements.
            options:
                -   label: Proof of ownership of the website is sent to a Kotatsu [Discord server](https://discord.gg/NNJ5RgVBC5) or [Telegram community](https://t.me/kotatsuapp)
                    required: true
                -   label: Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
                    required: true
